---
title: "Neural Network Kirsh 3x3"
author: "Zach Diener"
date: "July 15, 2015"
output: html_document
---

```{r}
library(wavethresh) 
library(gplots)
library(wavelets)
library(nnet)


#Generate Simulation data
set.seed(5)

rm(list=ls())	#Clear data

sds<-sample(rep(c(0,0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6,1.8,2.0),30))	#Generate random list of standard deviations
TestCases<-data.frame(matrix(NA,nrow=330,ncol=70))	#Create empty data frame to store simulated signals
NoiseSeeds<-data.frame(matrix(NA,nrow=330,ncol=626))	#Create empty data frame to store state of RNG before each injection of noise
SD_Change<-data.frame(matrix(NA,nrow=330,ncol=2))	#Create empty data frame to store standard deviations and transition points
colnames(SD_Change)<-c("sd","change")	#Name columns 
x<-(1:70)	#Create vector of values from 1 to 70
for(i in 1:330){	#Loop over all standard deviations
		change1<-sample(25:55,1)	#Randomly select transition point between 25 and 55
		NoiseSeeds[i,]<-.Random.seed	#Store state of RNG
		TestCases[i,(1:70)]<-(((x>=1 & x<(change1-25))*0)+((x>=(change1-25) & x<(change1-10))*((0.02*x)+0.5-(0.02*change1)))+((x>=(change1-10) & x<(change1-6))*(x+10.3-change1))+((x>=(change1-6) & x<(change1))*(4.3))+((x>=(change1) & x<(change1+10))*((-0.5*x)+4.3+(0.5*change1)))+((x>=(change1+10) & x<=(change1+15))*((-0.25*x)+1.8+(0.25*change1)))+((x>(change1+15) & x<=1000)*(-1.95)))+rnorm(length(x),sd=sds[i])+20	#Inject noise into base signal and store
	#	TestCases[i,71]<-paste(";",(i),sep="")	#Label signal for later identification
		SD_Change[i,"change"]<-change1	#Store transition point
}	#End loop
SD_Change[,"sd"]<-sds	#Store standard deviation of injected noise
write.csv(NoiseSeeds,row.names=FALSE,"./NoiseSeeds.csv")	#Save output
write.csv(TestCases,row.names=FALSE,"./TestCases.csv")	#Save output
write.csv(SD_Change,row.names=FALSE,"./SD_Change.csv")	#Save output
df <- as.data.frame(read.csv("TestCases.csv", header=T)) # read in data frame


Gradient3X3 <- matrix(c(0),990,70)

for(z in 1:330){
  for(t in 1:3){
#input number of frequency bands
j= c(1:6)

#input the original signal 
s <- as.vector(as.matrix((df[31,])))

#Averages<-t(Averages)
Averages = matrix(0,length(j),length(s))
nrows <- nrow(Averages)
rownames(Averages) <- 0: (nrow(Averages)-1)
colnames(Averages) <- 1:ncol(Averages)
Averages[1,] <- s


#Calculate Averages
for (j in 1:((nrows)-1)){
  for (n in (2*j):length(s)){
    #print(Averages[1, (n-(((2*j)-1)):n)])
   Averages[(j+1),n] <- mean(Averages[1, (n-((2*j)-1)):n]) 
    }
}

#Threshold Averages
Arow_1 <- Averages[2,2:70]
sigma <- (mad(Arow_1))/.6745
#print(mad(Arow_1))
Thresh<- sigma * (sqrt(2* log(length(Arow_1))))

for (i in 1:4){
  high <- Averages[i,] >= Thresh
  mid <- Averages[i,] < Thresh
  low <- Averages[i,] <= -Thresh
  Averages[i,high] <- (Averages[i,high] <- (Averages[i,high]-Thresh))
  Averages[i,mid] <- (Averages[i,mid] <- 0)
  Averages[i,low] <- (Averages[i,low] <- (Averages[i,low]+Thresh))
}


#Calculate Differences
Differences <- matrix(c(0),nrow(Averages)-1,ncol(Averages))

for (j in 1:((nrows)-1)){
  for (n in (2*(j)):length(s)){
    Differences[(j),n] <- (-1)*((mean(Averages[1, (n-((2*j)-1)):(n-j)])-mean(Averages[1, (n-(j)+1):n]))/2)
  }
}


#Data Prep For Neural Network (Kirsch Operators)

#Direction 3
horiz3<- t(as.matrix(c(5,-3,-3,5,0,-3,5,-3,-3)))

a<- matrix(c(0),3,3)
k<-2
Differences3X3_3 <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3_3[n,i] <- horiz3 %*% Z
    }
  }
}

#Direction 4
horiz4<- t(as.matrix(c(-3,-3,-3,5,0,-3,5,5,-3)))

a<- matrix(c(0),3,3)
k<-2
Differences3X3_4 <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3_4[n,i] <- horiz4 %*% Z
    }
  }
}


#Direction 7
horiz7<- t(as.matrix(c(-3,-3,5,-3,0,5,-3,-3,5)))

a<- matrix(c(0),3,3)
k<-2
Differences3X3_7 <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3_7[n,i] <- horiz7 %*% Z
    }
  }
}

#Direction 8
horiz8<- t(as.matrix(c(-3,5,5,-3,0,5,-3,-3,-3)))

a<- matrix(c(0),3,3)
k<-2
Differences3X3_8 <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3_8[n,i] <- horiz8 %*% Z
    }
  }
}


Differences3X3_3 <- Differences3X3_3[c(-1,-5),]
Differences3X3_4 <- Differences3X3_4[c(-1,-5),]
Differences3X3_7 <- Differences3X3_7[c(-1,-5),]
Differences3X3_8 <- Differences3X3_8[c(-1,-5),]

Gradient3X3[3*(z-1)+t,] <- sqrt((Differences3X3_3[t,])^2+(Differences3X3_4[t,])^2+(Differences3X3_7[t,])^2+(Differences3X3_8[t,])^2)
  }
}


#Neural Network Construction
x<- Gradient3X3
y <- matrix(c(0),990,70)

SD_Change3 <- as.matrix(rep(SD_Change[,2],each=3))

for(q in 1:990){
  j <- SD_Change3[q,1]
  y[q,j] <- 1
}


NE <- nnet(x[1:600,], y[1:600,], size = 45, wts=W,
     linout = FALSE, entropy = FALSE, softmax = FALSE,
     censored = FALSE, skip = FALSE, rang = 0.7, decay = .000005,
     maxit = 6000, Hess = FALSE, trace = TRUE, MaxNWts = 100000,
     abstol = 1.0e-4, reltol = 1.0e-8)

W <- NE$wts

NEPredict <- predict(NE, Gradient3X3[601:990,], type = "raw")

Pvalue <- matrix(c(0),390,1)

for (q in 1:390){
  Exvec<- as.vector(NEPredict[q,])
  Pvalue[q,] <- which.max(Exvec)
}

Error <- SD_Change3[601:990,]-Pvalue

ErrorPer <- sum(Error)/nrow(Error)

